version: "2"
services:
  test:
    build:
      context: .
      dockerfile: git-custom-commands-test/Dockerfile
    volumes:
      - ./git-custom-commands-test:/test
  test-reviewable:
    build:
      context: reviewable
      dockerfile: Dockerfile
  lambda-slack-retro-bot-to-airtable-test:
    build:
      context: lambda-slack-retro-bot-to-airtable
      dockerfile: Dockerfile.test
    volumes:
      - ./lambda-slack-retro-bot-to-airtable/lint_and_test.sh:/test/lint_and_test.sh:ro
      - ./lambda-slack-retro-bot-to-airtable/slack_retro_bot_to_airtable.py:/test/slack_retro_bot_to_airtable.py:ro
      - ./lambda-slack-retro-bot-to-airtable/slack_retro_bot_to_airtable_test.py:/test/slack_retro_bot_to_airtable_test.py:ro
      - ./lambda-slack-retro-bot-to-airtable/slack_retro_bot_notification_example.txt:/test/slack_retro_bot_notification_example.txt:ro
      - ./.pylintrc:/test/.pylintrc:ro
      - ./.pep8:/test/.pep8:ro
    environment:
      AIRTABLE_RETRO_BASE_ID: $AIRTABLE_RETRO_BASE_ID
      AIRTABLE_RETRO_API_KEY: $AIRTABLE_RETRO_API_KEY
      SLACK_RETRO_TOKEN: $SLACK_RETRO_TOKEN
    tty: true
  lambda-slack-retro-bot-to-airtable-deploy:
    build:
      context: lambda-slack-retro-bot-to-airtable
      dockerfile: Dockerfile.deploy
    volumes:
      - ./lambda-slack-retro-bot-to-airtable/slack_retro_bot_to_airtable.py:/var/task/slack_retro_bot_to_airtable.py:ro
      - ./lambda-slack-retro-bot-to-airtable/zappa_settings.json:/var/task/zappa_settings.json:ro
    environment:
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    tty: true
